# Complete services for ThesslaGreen Modbus Integration
# Compatibility: Home Assistant 2025.7.1+ & pymodbus 3.5.*+
# All models: ThesslaGreen AirPack Home series 4

set_special_mode:
  name: Set Special Mode
  description: Set unit to a special mode.
  target: &tg_target
    entity:
      domain: climate
      integration: thessla_green_modbus
  fields:
    mode:
      name: Special Mode
      description: Mode to activate.
      required: true
      selector:
        select:
          options: !include options/special_modes.json
    duration:
      name: Duration (minutes)
      description: Minutes to run mode; 0 for unlimited.
      required: false
      default: 0
      selector:
        number:
          min: 0
          max: 480
          step: 1

set_airflow_schedule:
  name: Set Airflow Schedule
  description: Configure weekly airflow schedule.
  target: *tg_target
  fields:
    day:
      name: Day of Week
      description: Day of week.
      required: true
      selector:
        select:
          options: !include options/days_of_week.json
    period:
      name: Period
      description: Day period (1 or 2).
      required: true
      selector:
        select:
          options: !include options/periods.json
    start_time:
      name: Start Time
      description: Period start time.
      required: true
      selector: &time_selector
        time:
    end_time:
      name: End Time
      description: Period end time.
      required: true
      selector: *time_selector
    airflow_rate:
      name: Airflow Rate
      description: Airflow in %.
      required: true
      selector:
        number:
          min: 10
          max: 100
          step: 5
    temperature:
      name: Temperature
      description: Target temperature °C.
      required: false
      selector:
        number:
          min: 16.0
          max: 30.0
          step: 0.5

set_bypass_parameters:
  name: Set Bypass Parameters
  description: Configure bypass parameters.
  target: *tg_target
  fields:
    mode:
      name: Bypass Mode
      description: Bypass mode.
      required: true
      selector:
        select:
          options: !include options/bypass_modes.json
    min_outdoor_temperature:
      name: Minimum Outdoor Temperature
      description: Minimum outdoor temperature for bypass activation °C.
      required: false
      selector:
        number:
          min: 10.0
          max: 40.0
          step: 0.5

set_gwc_parameters:
  name: Set GWC Parameters
  description: Configure ground heat exchanger.
  target: *tg_target
  fields:
    mode:
      name: GWC Mode
      description: GWC mode.
      required: true
      selector:
        select:
          options: !include options/gwc_modes.json
    min_air_temperature:
      name: Minimum Air Temperature
      description: Lower outdoor temperature threshold °C.
      required: false
      selector:
        number:
          min: 0.0
          max: 20.0
          step: 0.5
    max_air_temperature:
      name: Maximum Air Temperature
      description: Upper outdoor temperature threshold °C.
      required: false
      selector:
        number:
          min: 30.0
          max: 80.0
          step: 0.5

set_air_quality_thresholds:
  name: Set Air Quality Thresholds
  description: Configure air quality thresholds.
  target: *tg_target
  fields:
    co2_low:
      name: CO2 Low Threshold
      description: Low CO2 ppm.
      required: false
      selector:
        number:
          min: 400
          max: 800
          step: 50
    co2_medium:
      name: CO2 Medium Threshold
      description: Medium CO2 ppm.
      required: false
      selector:
        number:
          min: 600
          max: 1200
          step: 50
    co2_high:
      name: CO2 High Threshold
      description: High CO2 ppm.
      required: false
      selector:
        number:
          min: 800
          max: 1600
          step: 50
    humidity_target:
      name: Target Humidity
      description: Target humidity %.
      required: false
      selector:
        number:
          min: 30
          max: 70
          step: 5

set_temperature_curve:
  name: Set Temperature Curve
  description: Configure heating curve.
  target: *tg_target
  fields:
    slope:
      name: Curve Slope
      description: Curve slope 0.1-3.0.
      required: true
      selector:
        number:
          min: 0.1
          max: 3.0
          step: 0.1
    offset:
      name: Curve Offset
      description: Curve offset °C.
      required: true
      selector:
        number:
          min: -10.0
          max: 10.0
          step: 0.5
    max_supply_temp:
      name: Max Supply Temperature
      description: Max supply temperature °C.
      required: false
      selector:
        number:
          min: 25.0
          max: 95.0
          step: 0.5
    min_supply_temp:
      name: Min Supply Temperature
      description: Min supply temperature °C.
      required: false
      selector:
        number:
          min: 15.0
          max: 35.0
          step: 0.5

reset_filters:
  name: Reset Filter Counter
  description: Reset filter lifetime counter.
  target: *tg_target
  fields:
    filter_type:
      name: Filter Type
      description: Filter to reset.
      required: true
      selector:
        select:
          options: !include options/filter_types.json

reset_settings:
  name: Reset Settings
  description: Reset user settings.
  target: *tg_target
  fields:
    reset_type:
      name: Reset Type
      description: Settings to reset.
      required: true
      selector:
        select:
          options: !include options/reset_types.json

start_pressure_test:
  name: Start Pressure Test
  description: Start automatic pressure test.
  target: *tg_target

set_modbus_parameters:
  name: Set Modbus Parameters
  description: Configure Modbus communication.
  target: *tg_target
  fields:
    port:
      name: Port
      description: Modbus port.
      required: true
      selector:
        select:
          options: !include options/modbus_ports.json
    baud_rate:
      name: Baud Rate
      description: Transmission speed.
      required: false
      selector:
        select:
          options: !include options/modbus_baud_rates.json
    parity:
      name: Parity
      description: Parity bit.
      required: false
      selector:
        select:
          options: !include options/modbus_parity.json
    stop_bits:
      name: Stop Bits
      description: Stop bits.
      required: false
      selector:
        select:
          options: !include options/modbus_stop_bits.json

set_device_name:
  name: Set Device Name
  description: Set device name using only printable ASCII characters (max 16).
  target: *tg_target
  fields:
    device_name:
      name: Device Name
      description: Device name (1–16 printable ASCII chars).
      required: true
      selector:
        text:
          multiline: false

refresh_device_data:
  name: Refresh Device Data
  description: Force immediate data refresh.
  target: *tg_target

scan_all_registers:
  name: Scan All Registers
  description: Perform full register scan and report unknown registers.
  target: *tg_target
