# Complete services for ThesslaGreen Modbus Integration
# Compatibility: Home Assistant 2025.* + pymodbus 3.5.*+
# All models: thessla green AirPack Home series 4

set_special_mode:
  name: Set Special Mode
  description: Sets special operating mode of heat recovery unit (BOOST, ECO, FIREPLACE, HOOD, etc.)
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    mode:
      name: Special Mode
      description: Type of special mode to activate
      required: true
      selector:
        select:
          options:
            - "none"
            - "boost"
            - "eco"
            - "away"
            - "fireplace"
            - "hood"
            - "party"
            - "bathroom"
            - "kitchen"
            - "summer"
            - "winter"
    duration:
      name: Duration (minutes)
      description: Duration of special mode in minutes (0 = unlimited)
      required: false
      default: 0
      selector:
        number:
          min: 0
          max: 480
          step: 5

set_airflow_schedule:
  name: Set Airflow Schedule
  description: Configures weekly airflow schedule
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    day:
      name: Day of Week
      description: Day of week to configure
      required: true
      selector:
        select:
          options:
            - "monday"
            - "tuesday" 
            - "wednesday"
            - "thursday"
            - "friday"
            - "saturday"
            - "sunday"
    period:
      name: Period
      description: Day period (1 or 2)
      required: true
      selector:
        select:
          options:
            - "1"
            - "2"
    start_time:
      name: Start Time
      description: Period start time (HH:MM)
      required: true
      selector:
        time:
    end_time:
      name: End Time
      description: Period end time (HH:MM)
      required: true
      selector:
        time:
    airflow_rate:
      name: Airflow Rate
      description: Airflow intensity in %
      required: true
      selector:
        number:
          min: 10
          max: 100
          step: 5
    temperature:
      name: Temperature
      description: Target temperature in °C
      required: false
      selector:
        number:
          min: 16.0
          max: 30.0
          step: 0.5

set_bypass_parameters:
  name: Set Bypass Parameters
  description: Configures bypass system parameters
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    mode:
      name: Bypass Mode
      description: Bypass operating mode
      required: true
      selector:
        select:
          options:
            - "auto"
            - "open"
            - "closed"
    temperature_threshold:
      name: Temperature Threshold
      description: Bypass activation temperature threshold in °C
      required: false
      selector:
        number:
          min: 18.0
          max: 30.0
          step: 0.5
    hysteresis:
      name: Hysteresis
      description: Temperature hysteresis in °C
      required: false
      selector:
        number:
          min: 1.0
          max: 5.0
          step: 0.5

set_gwc_parameters:
  name: Set GWC Parameters
  description: Configures ground heat exchanger parameters
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    mode:
      name: GWC Mode
      description: Ground heat exchanger operating mode
      required: true
      selector:
        select:
          options:
            - "disabled"
            - "auto"
            - "forced"
    temperature_threshold:
      name: Temperature Threshold
      description: GWC activation temperature threshold in °C
      required: false
      selector:
        number:
          min: -5.0
          max: 15.0
          step: 0.5
    hysteresis:
      name: Hysteresis
      description: Temperature hysteresis in °C
      required: false
      selector:
        number:
          min: 1.0
          max: 5.0
          step: 0.5

set_air_quality_thresholds:
  name: Set Air Quality Thresholds
  description: Configures thresholds for air quality control system
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    co2_low:
      name: CO2 Low Threshold
      description: Low CO2 threshold in ppm
      required: false
      selector:
        number:
          min: 400
          max: 800
          step: 50
    co2_medium:
      name: CO2 Medium Threshold
      description: Medium CO2 threshold in ppm
      required: false
      selector:
        number:
          min: 600
          max: 1200
          step: 50
    co2_high:
      name: CO2 High Threshold
      description: High CO2 threshold in ppm
      required: false
      selector:
        number:
          min: 800
          max: 1600
          step: 50
    humidity_target:
      name: Target Humidity
      description: Target humidity in %
      required: false
      selector:
        number:
          min: 30
          max: 70
          step: 5

set_temperature_curve:
  name: Set Temperature Curve
  description: Configures heating curve for heating system
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    slope:
      name: Curve Slope
      description: Heating curve slope (0.1-3.0)
      required: true
      selector:
        number:
          min: 0.1
          max: 3.0
          step: 0.1
    offset:
      name: Curve Offset
      description: Heating curve offset in °C
      required: true
      selector:
        number:
          min: -10.0
          max: 10.0
          step: 0.5
    max_supply_temp:
      name: Max Supply Temperature
      description: Maximum supply temperature in °C
      required: false
      selector:
        number:
          min: 25.0
          max: 95.0
          step: 0.5
    min_supply_temp:
      name: Min Supply Temperature
      description: Minimum supply temperature in °C
      required: false
      selector:
        number:
          min: 15.0
          max: 35.0
          step: 0.5

reset_filters:
  name: Reset Filter Counter
  description: Resets filter lifetime counter
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    filter_type:
      name: Filter Type
      description: Type of filter to set
      required: true
      selector:
        select:
          options:
            - "presostat"
            - "flat_filters"
            - "cleanpad"
            - "cleanpad_pure"

reset_settings:
  name: Reset Settings
  description: Resets user settings to default values
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    reset_type:
      name: Reset Type
      description: Type of settings to reset
      required: true
      selector:
        select:
          options:
            - "user_settings"
            - "schedule_settings"
            - "all_settings"

start_pressure_test:
  name: Start Pressure Test
  description: Starts automatic filter/pressure control test
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus

set_modbus_parameters:
  name: Set Modbus Parameters
  description: Configures Modbus communication parameters (for advanced users only)
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    port:
      name: Port
      description: Modbus port (Air-B or Air++)
      required: true
      selector:
        select:
          options:
            - "air_b"
            - "air_plus"
    baud_rate:
      name: Baud Rate
      description: Modbus transmission speed
      required: false
      selector:
        select:
          options:
            - "4800"
            - "9600"
            - "14400"
            - "19200"
            - "28800"
            - "38400"
            - "57600"
            - "76800"
            - "115200"
    parity:
      name: Parity
      description: Parity bit
      required: false
      selector:
        select:
          options:
            - "none"
            - "even"
            - "odd"
    stop_bits:
      name: Stop Bits
      description: Number of stop bits
      required: false
      selector:
        select:
          options:
            - "1"
            - "2"

set_device_name:
  name: Set Device Name
  description: Sets custom device name (max 16 ASCII characters)
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    device_name:
      name: Device Name
      description: New device name (max 16 characters)
      required: true
      selector:
        text:
          multiline: false

refresh_device_data:
  name: Refresh Device Data
  description: Forces immediate refresh of device data
  fields:
    entity_id:
      name: Climate Entity
      description: Heat recovery unit climate entity
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus