# Kompletne serwisy dla ThesslaGreen Modbus Integration
# Kompatybilność: Home Assistant 2025.* + pymodbus 3.5.*+
# Wszystkie modele: thessla green AirPack Home serie 4

set_special_mode:
  name: Ustaw tryb specjalny
  description: Ustawia specjalny tryb pracy rekuperatora (BOOST, ECO, KOMINEK, OKAP, itp.)
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    mode:
      name: Tryb specjalny
      description: Typ trybu specjalnego do aktywacji
      required: true
      selector:
        select:
          options:
            - "none"
            - "boost"
            - "eco"
            - "away"
            - "fireplace"
            - "hood"
            - "party"
            - "bathroom"
            - "kitchen"
            - "summer"
            - "winter"
    duration:
      name: Czas trwania (minuty)
      description: Czas trwania trybu specjalnego w minutach (0 = bez limitu)
      required: false
      default: 0
      selector:
        number:
          min: 0
          max: 480
          step: 5

set_airflow_schedule:
  name: Ustaw harmonogram przepływu
  description: Konfiguruje tygodniowy harmonogram przepływu powietrza
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    day:
      name: Dzień tygodnia
      description: Dzień tygodnia do konfiguracji
      required: true
      selector:
        select:
          options:
            - "monday"
            - "tuesday" 
            - "wednesday"
            - "thursday"
            - "friday"
            - "saturday"
            - "sunday"
    period:
      name: Okres
      description: Okres dnia (1 lub 2)
      required: true
      selector:
        select:
          options:
            - "1"
            - "2"
    start_time:
      name: Czas rozpoczęcia
      description: Czas rozpoczęcia okresu (HH:MM)
      required: true
      selector:
        time:
    end_time:
      name: Czas zakończenia
      description: Czas zakończenia okresu (HH:MM)
      required: true
      selector:
        time:
    airflow_rate:
      name: Przepływ powietrza
      description: Intensywność przepływu powietrza w %
      required: true
      selector:
        number:
          min: 10
          max: 100
          step: 5
    temperature:
      name: Temperatura
      description: Zadana temperatura w °C
      required: false
      selector:
        number:
          min: 16.0
          max: 30.0
          step: 0.5

set_bypass_parameters:
  name: Ustaw parametry bypass
  description: Konfiguruje parametry systemu bypass
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    mode:
      name: Tryb bypass
      description: Tryb pracy bypass
      required: true
      selector:
        select:
          options:
            - "auto"
            - "open"
            - "closed"
    temperature_threshold:
      name: Próg temperatury
      description: Próg temperatury aktywacji bypass w °C
      required: false
      selector:
        number:
          min: 18.0
          max: 30.0
          step: 0.5
    hysteresis:
      name: Histereza
      description: Histereza temperatury w °C
      required: false
      selector:
        number:
          min: 1.0
          max: 5.0
          step: 0.5

set_gwc_parameters:
  name: Ustaw parametry GWC
  description: Konfiguruje parametry gruntowego wymiennika ciepła
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    mode:
      name: Tryb GWC
      description: Tryb pracy gruntowego wymiennika ciepła
      required: true
      selector:
        select:
          options:
            - "disabled"
            - "auto"
            - "forced"
    temperature_threshold:
      name: Próg temperatury
      description: Próg temperatury aktywacji GWC w °C
      required: false
      selector:
        number:
          min: -5.0
          max: 15.0
          step: 0.5
    hysteresis:
      name: Histereza
      description: Histereza temperatury w °C
      required: false
      selector:
        number:
          min: 1.0
          max: 5.0
          step: 0.5

set_air_quality_thresholds:
  name: Ustaw progi jakości powietrza
  description: Konfiguruje progi dla systemu kontroli jakości powietrza
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    co2_low:
      name: CO2 - próg niski
      description: Niski próg CO2 w ppm
      required: false
      selector:
        number:
          min: 400
          max: 800
          step: 50
    co2_medium:
      name: CO2 - próg średni
      description: Średni próg CO2 w ppm
      required: false
      selector:
        number:
          min: 600
          max: 1200
          step: 50
    co2_high:
      name: CO2 - próg wysoki
      description: Wysoki próg CO2 w ppm
      required: false
      selector:
        number:
          min: 800
          max: 1600
          step: 50
    humidity_target:
      name: Docelowa wilgotność
      description: Docelowa wilgotność w %
      required: false
      selector:
        number:
          min: 30
          max: 70
          step: 5

set_temperature_curve:
  name: Ustaw krzywą grzania
  description: Konfiguruje krzywą grzania dla systemu ogrzewania
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    slope:
      name: Nachylenie krzywej
      description: Nachylenie krzywej grzania (0.1-3.0)
      required: true
      selector:
        number:
          min: 0.1
          max: 3.0
          step: 0.1
    offset:
      name: Przesunięcie krzywej
      description: Przesunięcie krzywej grzania w °C
      required: true
      selector:
        number:
          min: -10.0
          max: 10.0
          step: 0.5
    max_supply_temp:
      name: Max. temp. nawiewu
      description: Maksymalna temperatura nawiewu w °C
      required: false
      selector:
        number:
          min: 25.0
          max: 95.0
          step: 0.5
    min_supply_temp:
      name: Min. temp. nawiewu
      description: Minimalna temperatura nawiewu w °C
      required: false
      selector:
        number:
          min: 15.0
          max: 35.0
          step: 0.5

reset_filters:
  name: Resetuj licznik filtrów
  description: Resetuje licznik czasu życia filtrów
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    filter_type:
      name: Typ filtra
      description: Typ filtra do ustawienia
      required: true
      selector:
        select:
          options:
            - "presostat"
            - "flat_filters"
            - "cleanpad"
            - "cleanpad_pure"

reset_settings:
  name: Resetuj ustawienia
  description: Resetuje ustawienia użytkownika do wartości domyślnych
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    reset_type:
      name: Typ resetu
      description: Typ ustawień do zresetowania
      required: true
      selector:
        select:
          options:
            - "user_settings"
            - "schedule_settings"
            - "all_settings"

start_pressure_test:
  name: Uruchom test ciśnienia
  description: Uruchamia automatyczny test kontroli filtrów/ciśnienia
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus

set_modbus_parameters:
  name: Ustaw parametry Modbus
  description: Konfiguruje parametry komunikacji Modbus (tylko dla zaawansowanych użytkowników)
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    port:
      name: Port
      description: Port Modbus (Air-B lub Air++)
      required: true
      selector:
        select:
          options:
            - "air_b"
            - "air_plus"
    baud_rate:
      name: Szybkość transmisji
      description: Szybkość transmisji Modbus
      required: false
      selector:
        select:
          options:
            - "4800"
            - "9600"
            - "14400"
            - "19200"
            - "28800"
            - "38400"
            - "57600"
            - "76800"
            - "115200"
    parity:
      name: Parzystość
      description: Bit parzystości
      required: false
      selector:
        select:
          options:
            - "none"
            - "even"
            - "odd"
    stop_bits:
      name: Bity stopu
      description: Liczba bitów stopu
      required: false
      selector:
        select:
          options:
            - "1"
            - "2"

set_device_name:
  name: Ustaw nazwę urządzenia
  description: Ustawia niestandardową nazwę urządzenia (max 16 znaków ASCII)
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus
    device_name:
      name: Nazwa urządzenia
      description: Nowa nazwa urządzenia (max 16 znaków)
      required: true
      selector:
        text:
          multiline: false

refresh_device_data:
  name: Odśwież dane urządzenia
  description: Wymusza natychmiastowe odświeżenie danych z urządzenia
  fields:
    entity_id:
      name: Encja climate
      description: Encja climate rekuperatora
      required: true
      selector:
        entity:
          domain: climate
          integration: thessla_green_modbus