# Services for ThesslaGreen Modbus Integration
# Kompatybilność: Home Assistant 2025.* + pymodbus 3.5.*+
# Wszystkie modele: thessla green AirPack Home serie 4

set_mode:
  name: Set Operating Mode
  description: Set the operating mode of the ThesslaGreen AirPack device
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    mode:
      name: Mode
      description: Operating mode to set
      required: true
      selector:
        select:
          options:
            - "auto"
            - "manual"
            - "temporary"

set_temperature:
  name: Set Temperature
  description: Set target temperature for the specified mode
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    temperature:
      name: Temperature
      description: Target temperature in Celsius
      required: true
      selector:
        number:
          min: 15
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
    mode:
      name: Temperature Mode
      description: Which temperature setting to change
      required: false
      default: "comfort"
      selector:
        select:
          options:
            - "comfort"
            - "heating"
            - "cooling"
            - "manual"
            - "auto"

set_flow_rate:
  name: Set Flow Rate
  description: Set air flow rate percentage
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    flow_rate:
      name: Flow Rate
      description: Air flow rate percentage
      required: true
      selector:
        number:
          min: 10
          max: 100
          step: 1
          unit_of_measurement: "%"
    mode:
      name: Flow Mode
      description: Which flow rate setting to change
      required: false
      default: "manual"
      selector:
        select:
          options:
            - "manual"
            - "auto"
            - "boost"

activate_special_mode:
  name: Activate Special Mode
  description: Activate a special operating mode (OKAP, KOMINEK, PARTY, etc.)
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    special_mode:
      name: Special Mode
      description: Special mode to activate
      required: true
      selector:
        select:
          options:
            - "okap"
            - "fireplace"
            - "party"
            - "boost"
            - "vacation"
            - "eco"
            - "night"
    duration:
      name: Duration
      description: Duration in minutes (for timed modes)
      required: false
      selector:
        number:
          min: 1
          max: 480
          step: 1
          unit_of_measurement: "min"
    intensity:
      name: Intensity
      description: Intensity percentage (for modes that support it)
      required: false
      selector:
        number:
          min: 10
          max: 100
          step: 5
          unit_of_measurement: "%"

deactivate_special_mode:
  name: Deactivate Special Mode
  description: Deactivate all special modes and return to normal operation
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus

set_schedule:
  name: Set Weekly Schedule
  description: Set weekly schedule for a specific day and period
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    day:
      name: Day of Week
      description: Day of the week to configure
      required: true
      selector:
        select:
          options:
            - "monday"
            - "tuesday"
            - "wednesday"
            - "thursday"
            - "friday"
            - "saturday"
            - "sunday"
    period:
      name: Period
      description: Time period (1-4) for the day
      required: true
      selector:
        number:
          min: 1
          max: 4
          step: 1
    start_time:
      name: Start Time
      description: Start time for this period (HH:MM)
      required: true
      selector:
        time:
    end_time:
      name: End Time
      description: End time for this period (HH:MM)
      required: true
      selector:
        time:
    intensity:
      name: Intensity
      description: Air flow intensity for this period
      required: true
      selector:
        number:
          min: 10
          max: 100
          step: 5
          unit_of_measurement: "%"
    temperature:
      name: Temperature
      description: Target temperature for this period
      required: true
      selector:
        number:
          min: 15
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

reset_settings:
  name: Reset Settings
  description: Reset device settings to factory defaults
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    reset_type:
      name: Reset Type
      description: Type of reset to perform
      required: true
      selector:
        select:
          options:
            - "user_settings"
            - "schedule"
            - "all"

set_gwc_mode:
  name: Set GWC Mode
  description: Set Ground Water Cooler (GWC) operating mode
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    mode:
      name: GWC Mode
      description: GWC operating mode
      required: true
      selector:
        select:
          options:
            - "off"
            - "auto"
            - "manual"
    switch_temperature:
      name: Switch Temperature
      description: Temperature threshold for automatic GWC switching
      required: false
      selector:
        number:
          min: -10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

set_bypass_mode:
  name: Set Bypass Mode
  description: Set heat recovery bypass operating mode
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    mode:
      name: Bypass Mode
      description: Bypass operating mode
      required: true
      selector:
        select:
          options:
            - "off"
            - "auto"
            - "manual"

set_filter_type:
  name: Set Filter Type
  description: Set the type of filters installed in the device
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    filter_type:
      name: Filter Type
      description: Type of filters installed
      required: true
      selector:
        select:
          options:
            - "presostat"
            - "flat_filters"
            - "cleanpad"
            - "cleanpad_pure"

read_diagnostics:
  name: Read Diagnostics
  description: Read diagnostic information from the device
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to read diagnostics from
      required: true
      selector:
        device:
          integration: thessla_green_modbus

refresh_data:
  name: Refresh Data
  description: Force immediate refresh of all device data
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to refresh
      required: true
      selector:
        device:
          integration: thessla_green_modbus

write_register:
  name: Write Register
  description: Write a value directly to a Modbus register (advanced users only)
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to control
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    register_address:
      name: Register Address
      description: Modbus register address (decimal or hex with 0x prefix)
      required: true
      selector:
        text:
    value:
      name: Value
      description: Value to write to the register
      required: true
      selector:
        number:
          min: 0
          max: 65535
          step: 1
    register_type:
      name: Register Type
      description: Type of register to write
      required: false
      default: "holding"
      selector:
        select:
          options:
            - "holding"
            - "coil"

read_register:
  name: Read Register
  description: Read a value directly from a Modbus register (advanced users only)
  fields:
    device_id:
      name: Device
      description: The ThesslaGreen device to read from
      required: true
      selector:
        device:
          integration: thessla_green_modbus
    register_address:
      name: Register Address
      description: Modbus register address (decimal or hex with 0x prefix)
      required: true
      selector:
        text:
    register_type:
      name: Register Type
      description: Type of register to read
      required: false
      default: "input"
      selector:
        select:
          options:
            - "input"
            - "holding"
            - "coil"
            - "discrete"