set_mode:
  name: Ustaw tryb pracy
  description: Ustawia tryb pracy rekuperatora
  fields:
    mode:
      name: Tryb
      description: Tryb pracy rekuperatora
      required: true
      selector:
        select:
          options:
            - auto
            - manual
            - temporary

set_intensity:
  name: Ustaw intensywność wentylacji
  description: Ustawia intensywność wentylacji w procentach
  fields:
    intensity:
      name: Intensywność (%)
      description: Intensywność przepływu powietrza (10-150)
      required: true
      selector:
        number:
          min: 10
          max: 150
          step: 1

set_special_function:
  name: Ustaw funkcję specjalną
  description: Ustawia specjalną funkcję rekuperatora
  fields:
    function:
      name: Funkcja
      description: Specjalna funkcja rekuperatora
      required: true
      selector:
        select:
          options:
            - none
            - hood
            - fireplace
            - airing_manual
            - airing_auto
            - empty_house
            - open_windows

reset_alarms:
  name: Resetuj alarmy
  description: Resetuje alarmy ostrzeżeń lub błędów
  fields:
    alarm_type:
      name: Typ alarmu
      description: Typ alarmu do zresetowania
      selector:
        select:
          options:
            - warnings
            - errors
            - all

device_rescan:
  name: Ponownie skanuj urządzenie
  description: Przeprowadza ponowne wykrywanie możliwości urządzenia
