# Enhanced services for ThesslaGreen Modbus Integration
# Wszystkie serwisy z kompletnej mapy rejestrów
# Kompatybilność: Home Assistant 2025.* + pymodbus 3.5.*+

set_mode:
  name: Set Operation Mode
  description: Ustawia tryb pracy rekuperatora
  fields:
    mode:
      name: Mode
      description: Tryb pracy
      required: true
      selector:
        select:
          options:
            - "off"
            - "manual"
            - "auto"
            - "temporary"
    intensity:
      name: Intensity
      description: Intensywność wentylacji (opcjonalne)
      selector:
        number:
          min: 10
          max: 150
          step: 5
          unit_of_measurement: "%"

set_special_mode:
  name: Set Special Mode
  description: Ustawia tryb specjalny z intensywnością i czasem trwania
  fields:
    special_mode:
      name: Special Mode
      description: Tryb specjalny
      required: true
      selector:
        select:
          options:
            - "none"
            - "okap"
            - "kominek"
            - "wietrzenie"
            - "pusty_dom"
            - "boost"
            - "night"
            - "party"
            - "vacation"
            - "economy"
            - "comfort"
    intensity:
      name: Intensity
      description: Intensywność wentylacji (opcjonalne)
      selector:
        number:
          min: 10
          max: 150
          step: 5
          unit_of_measurement: "%"
    duration:
      name: Duration
      description: Czas trwania w minutach (opcjonalne)
      selector:
        number:
          min: 5
          max: 1440
          step: 5
          unit_of_measurement: "min"

set_temperature:
  name: Set Temperature
  description: Ustawia temperaturę docelową dla wybranego trybu
  fields:
    temperature:
      name: Temperature
      description: Temperatura docelowa
      required: true
      selector:
        number:
          min: 15.0
          max: 45.0
          step: 0.5
          unit_of_measurement: "°C"
    mode:
      name: Mode
      description: Tryb temperatury
      selector:
        select:
          options:
            - "manual"
            - "auto"
            - "temporary"
            - "comfort"

set_fan_speed:
  name: Set Fan Speed
  description: Ustawia prędkość wentylatorów i balans przepływów
  fields:
    supply_speed:
      name: Supply Fan Speed
      description: Prędkość wentylatora nawiewnego
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
    exhaust_speed:
      name: Exhaust Fan Speed
      description: Prędkość wentylatora wywiewnego
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
    balance:
      name: Flow Balance
      description: Balans przepływów
      selector:
        number:
          min: -20
          max: 20
          step: 1
          unit_of_measurement: "%"

control_bypass:
  name: Control Bypass
  description: Steruje trybem pracy bypass
  fields:
    mode:
      name: Bypass Mode
      description: Tryb pracy bypass
      required: true
      selector:
        select:
          options:
            - "auto"
            - "open"
            - "closed"

control_gwc:
  name: Control GWC
  description: Steruje systemem GWC (Ground Water Cooler)
  fields:
    mode:
      name: GWC Mode
      description: Tryb pracy GWC
      required: true
      selector:
        select:
          options:
            - "auto"
            - "on"
            - "off"

reset_alarms:
  name: Reset Alarms
  description: Resetuje alarmy i błędy systemu
  fields:
    alarm_type:
      name: Alarm Type
      description: Typ alarmów do zresetowania
      selector:
        select:
          options:
            - "all"
            - "errors"
            - "warnings"

set_schedule:
  name: Set Schedule
  description: Ustawia harmonogram pracy dla wybranego dnia i okresu
  fields:
    day:
      name: Day
      description: Dzień tygodnia
      required: true
      selector:
        select:
          options:
            - "mon"
            - "tue"
            - "wed"
            - "thu"
            - "fri"
            - "sat"
            - "sun"
    period:
      name: Period
      description: Okres czasowy (1-4)
      required: true
      selector:
        number:
          min: 1
          max: 4
          step: 1
    start_time:
      name: Start Time
      description: Czas rozpoczęcia (HH:MM)
      required: true
      selector:
        time:
    end_time:
      name: End Time
      description: Czas zakończenia (HH:MM)
      required: true
      selector:
        time:
    intensity:
      name: Intensity
      description: Intensywność wentylacji (opcjonalne)
      selector:
        number:
          min: 10
          max: 150
          step: 5
          unit_of_measurement: "%"
    temperature:
      name: Temperature
      description: Temperatura docelowa (opcjonalne)
      selector:
        number:
          min: 15.0
          max: 45.0
          step: 0.5
          unit_of_measurement: "°C"

rescan_device:
  name: Rescan Device
  description: Ponownie skanuje urządzenie w celu wykrycia dostępnych rejestrów
  fields: {}

get_diagnostic_info:
  name: Get Diagnostic Info
  description: Pobiera informacje diagnostyczne o urządzeniu i integracji
  fields: {}

backup_settings:
  name: Backup Settings
  description: Tworzy kopię zapasową ustawień urządzenia
  fields:
    include_schedule:
      name: Include Schedule
      description: Dołącz harmonogram do kopii zapasowej
      selector:
        boolean:
    include_alarms:
      name: Include Alarms
      description: Dołącz ustawienia alarmów do kopii zapasowej
      selector:
        boolean:

restore_settings:
  name: Restore Settings
  description: Przywraca ustawienia urządzenia z kopii zapasowej
  fields:
    backup_data:
      name: Backup Data
      description: Dane kopii zapasowej (format JSON)
      required: true
      selector:
        object:
    restore_schedule:
      name: Restore Schedule
      description: Przywróć harmonogram z kopii zapasowej
      selector:
        boolean:

calibrate_sensors:
  name: Calibrate Sensors
  description: Kalibruje czujniki temperatury z offsetami
  fields:
    outside_offset:
      name: Outside Temperature Offset
      description: Offset dla czujnika temperatury zewnętrznej
      selector:
        number:
          min: -10.0
          max: 10.0
          step: 0.1
          unit_of_measurement: "°C"
    supply_offset:
      name: Supply Temperature Offset
      description: Offset dla czujnika temperatury nawiewu
      selector:
        number:
          min: -10.0
          max: 10.0
          step: 0.1
          unit_of_measurement: "°C"
    exhaust_offset:
      name: Exhaust Temperature Offset
      description: Offset dla czujnika temperatury wywiewu
      selector:
        number:
          min: -10.0
          max: 10.0
          step: 0.1
          unit_of_measurement: "°C"