"""Validate Home Assistant dashboard entity IDs against integration mappings.

Usage:
    python tools/validate_dashboard_entities.py <dashboard_yaml_file>
"""

from __future__ import annotations

import argparse
import re
import sys
import types
from pathlib import Path


def _install_homeassistant_stubs() -> None:
    """Install lightweight Home Assistant stubs for standalone execution."""

    ha_root = types.ModuleType("homeassistant")

    const = types.ModuleType("homeassistant.const")
    const.CONF_HOST = "host"
    const.CONF_NAME = "name"
    const.CONF_PORT = "port"
    const.PERCENTAGE = "%"

    class UnitOfElectricPotential:
        VOLT = "V"

    class UnitOfPower:
        WATT = "W"

    class UnitOfTemperature:
        CELSIUS = "°C"

    class UnitOfTime:
        HOURS = "h"
        DAYS = "d"
        SECONDS = "s"

    class UnitOfVolumeFlowRate:
        CUBIC_METERS_PER_HOUR = "m³/h"

    const.UnitOfElectricPotential = UnitOfElectricPotential
    const.UnitOfPower = UnitOfPower
    const.UnitOfTemperature = UnitOfTemperature
    const.UnitOfTime = UnitOfTime
    const.UnitOfVolumeFlowRate = UnitOfVolumeFlowRate

    binary_sensor = types.ModuleType("homeassistant.components.binary_sensor")

    class BinarySensorDeviceClass:
        RUNNING = "running"
        OPENING = "opening"
        POWER = "power"
        HEAT = "heat"
        CONNECTIVITY = "connectivity"
        PROBLEM = "problem"
        SAFETY = "safety"
        MOISTURE = "moisture"

    binary_sensor.BinarySensorDeviceClass = BinarySensorDeviceClass

    sensor = types.ModuleType("homeassistant.components.sensor")

    class SensorDeviceClass:
        TEMPERATURE = "temperature"
        VOLTAGE = "voltage"
        POWER = "power"
        ENERGY = "energy"
        EFFICIENCY = "efficiency"
        VOLUME_FLOW_RATE = "volume_flow_rate"

    class SensorStateClass:
        MEASUREMENT = "measurement"
        TOTAL_INCREASING = "total_increasing"

    sensor.SensorDeviceClass = SensorDeviceClass
    sensor.SensorStateClass = SensorStateClass

    helpers_entity = types.ModuleType("homeassistant.helpers.entity")

    class EntityCategory:
        DIAGNOSTIC = "diagnostic"
        CONFIG = "config"

    helpers_entity.EntityCategory = EntityCategory

    core = types.ModuleType("homeassistant.core")

    class HomeAssistant:
        """Placeholder HomeAssistant type for typing-only imports."""

    core.HomeAssistant = HomeAssistant

    sys.modules.setdefault("homeassistant", ha_root)
    sys.modules.setdefault("homeassistant.const", const)
    sys.modules.setdefault("homeassistant.components.binary_sensor", binary_sensor)
    sys.modules.setdefault("homeassistant.components.sensor", sensor)
    sys.modules.setdefault("homeassistant.helpers.entity", helpers_entity)
    sys.modules.setdefault("homeassistant.core", core)


ENTITY_ID_PATTERN = re.compile(r"entity:\s*([a-z_]+\.[a-z0-9_]+)")
SUSPICIOUS_FALLBACK_PATTERN = re.compile(
    r"^(?:number\.rekuperator_\d+|select\.rekuperator(?:_\d+)?)$"
)


def _collect_entities(content: str) -> list[str]:
    """Return all entity IDs found in dashboard YAML text."""

    return ENTITY_ID_PATTERN.findall(content)


def _current_entity_ids() -> set[str]:
    """Return all current entity IDs generated by this integration."""

    _install_homeassistant_stubs()
    from custom_components.thessla_green_modbus.entity_mappings import ENTITY_MAPPINGS

    ids: set[str] = set()
    for domain, mapping in ENTITY_MAPPINGS.items():
        for key in mapping:
            ids.add(f"{domain}.rekuperator_{key}")
    return ids


def validate_dashboard(
    path: Path,
) -> tuple[list[str], list[tuple[str, str]], list[str], list[str]]:
    """Validate dashboard entities.

    Returns tuple: (valid, legacy_with_replacement, unknown, suspicious_fallback).
    """

    content = path.read_text(encoding="utf-8")
    entities = sorted(set(_collect_entities(content)))

    _install_homeassistant_stubs()
    from custom_components.thessla_green_modbus.entity_mappings import map_legacy_entity_id

    current = _current_entity_ids()
    valid: list[str] = []
    legacy: list[tuple[str, str]] = []
    unknown: list[str] = []
    suspicious_fallback: list[str] = []

    for entity_id in entities:
        if entity_id in current:
            valid.append(entity_id)
            continue
        mapped = map_legacy_entity_id(entity_id)
        if mapped != entity_id:
            legacy.append((entity_id, mapped))
            continue
        unknown.append(entity_id)
        if SUSPICIOUS_FALLBACK_PATTERN.match(entity_id):
            suspicious_fallback.append(entity_id)

    return valid, legacy, unknown, suspicious_fallback


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dashboard_yaml", type=Path, help="Path to dashboard YAML")
    args = parser.parse_args()

    valid, legacy, unknown, suspicious_fallback = validate_dashboard(args.dashboard_yaml)

    print(f"VALID: {len(valid)}")
    print(f"LEGACY (auto-mapped): {len(legacy)}")
    print(f"UNKNOWN: {len(unknown)}")

    if legacy:
        print("\nLegacy entity IDs:")
        for old, new in legacy:
            print(f"  - {old} -> {new}")

    if unknown:
        print("\nUnknown entity IDs:")
        for entity_id in unknown:
            print(f"  - {entity_id}")
    if suspicious_fallback:
        print("\nSuspicious fallback-like entity IDs:")
        for entity_id in suspicious_fallback:
            print(f"  - {entity_id}")

    return 1 if unknown else 0


if __name__ == "__main__":
    raise SystemExit(main())
