"""Register helpers and constants for the ThesslaGreen Modbus integration."""

from ..register_addresses import (
    REG_MAX_PERCENT,
    REG_MIN_PERCENT,
    REG_ON_OFF_PANEL_MODE,
    REG_TEMPORARY_FLOW_FLAG,
    REG_TEMPORARY_FLOW_MODE,
    REG_TEMPORARY_FLOW_START,
    REG_TEMPORARY_FLOW_VALUE,
    REG_TEMPORARY_TEMP_FLAG,
    REG_TEMPORARY_TEMP_MODE,
    REG_TEMPORARY_TEMP_START,
    REG_TEMPORARY_TEMP_VALUE,
)

__all__ = [
    "REG_MAX_PERCENT",
    "REG_MIN_PERCENT",
    "REG_ON_OFF_PANEL_MODE",
    "REG_TEMPORARY_FLOW_FLAG",
    "REG_TEMPORARY_FLOW_MODE",
    "REG_TEMPORARY_FLOW_START",
    "REG_TEMPORARY_FLOW_VALUE",
    "REG_TEMPORARY_TEMP_FLAG",
    "REG_TEMPORARY_TEMP_MODE",
    "REG_TEMPORARY_TEMP_START",
    "REG_TEMPORARY_TEMP_VALUE",
]
