"""Register helpers and constants for the ThesslaGreen Modbus integration."""

REG_MIN_PERCENT = 276
REG_MAX_PERCENT = 277
REG_ON_OFF_PANEL_MODE = 4387

REG_TEMPORARY_FLOW_MODE = 4400
REG_TEMPORARY_FLOW_VALUE = 4401
REG_TEMPORARY_FLOW_FLAG = 4402
REG_TEMPORARY_FLOW_START = REG_TEMPORARY_FLOW_MODE

REG_TEMPORARY_TEMP_MODE = 4403
REG_TEMPORARY_TEMP_VALUE = 4404
REG_TEMPORARY_TEMP_FLAG = 4405
REG_TEMPORARY_TEMP_START = REG_TEMPORARY_TEMP_MODE

__all__ = [
    "REG_MAX_PERCENT",
    "REG_MIN_PERCENT",
    "REG_ON_OFF_PANEL_MODE",
    "REG_TEMPORARY_FLOW_FLAG",
    "REG_TEMPORARY_FLOW_MODE",
    "REG_TEMPORARY_FLOW_START",
    "REG_TEMPORARY_FLOW_VALUE",
    "REG_TEMPORARY_TEMP_FLAG",
    "REG_TEMPORARY_TEMP_MODE",
    "REG_TEMPORARY_TEMP_START",
    "REG_TEMPORARY_TEMP_VALUE",
]
